### ISSUE TITLE
Critical problem: dynamiclightsreforged.mixins.json:lightsource.EntityMixin 

### ISSUE THREAD

**Issue by JJon149** [TeamDeusVult/MagnesiumExtras#28]
I've been trying to figure out what mods magnesium has been conflicting with, ill attach the latest.log as no crash report was generated. I keep getting exit code 1, no progress in launching. I have about 150 mods, mostly bugfixes/performance mods that I have previously tested with rubidium and magnesium, not to sure what is happening if someone could take a quick look at my log and maybe my mod list. 
The issue line is this : Critical problem: dynamiclightsreforged.mixins.json:lightsource.EntityMixin target net.minecraft.world.entity.Entity was loaded too early
[latest.log](https://github.com/TeamDeusVult/MagnesiumExtras/files/9274863/latest.log)
.

**Comment by isaaclepes** [comment]
The only mixin error I have dealt with was caused by Rubidium Extras and the recent JEI, but the error mentioned JEI. (see #26 )

Usually you have to remove your mods and add them back in batches until the error crops back up, then start weeding through the last batch until you find the ones related to the issue.

I don't know if it would help, but here are the mods I am using.  (Note: For Rubidium Extras, I am using the patched version shared in issue #26 )

![image](https://user-images.githubusercontent.com/54421422/184218921-8b41008a-114c-4a72-a8fd-30f82eb26af7.png)
